name: Trigger rebuild

on:
  schedule:
        - cron: '03 */4 * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build on dockerhub
        run: |
          sudo apt-get install curl
          curl -L -X POST https://hub.docker.com/api/build/v1/source/bae8da83-86af-432b-81c5-99883ad5dfe4/trigger/c0360b1f-9d0c-4b51-9431-b9b541137052/call/
